title: Noble Street Boutique
name: Courtney Starrett
email: leviathan747@gmail.com

parallax_image: assets/images/brick-wall.jpg

new_arrivals: NEW ARRIVALS
new_arrivals_description: See what's knew!
new_arrivals_url: newarrivals/

tops: TOPS
tops_description: Buy some sweet tops!
tops_url: tops/

bottoms: BOTTOMS
bottoms_description: Buy some rockin bottoms!
bottoms_url: bottoms/

accessories: ACCESSORIES
accessories_description: Get your accessories here!
accessories_url: accessories/

dresses: DRESSES
dresses_description: Rock summer with these dresses!
dresses_url: dresses/

collections:
  newarrivals:
    output: true
  tops:
    output: true
  bottoms:
    output: true
  accessories:
    output: true
  dresses:
    output: true

shop_button: Shop Now!

#url: https://noblestreetboutique.com
baseurl:
url: http://localhost:4000/ #the url of your site

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
