title: Noble Street Boutique
name: Courtney Starrett
email: noblestreetboutique@gmail.com

parallax_image: assets/images/brick-wall.jpg

new_arrivals_title: NEW ARRIVALS
new_arrivals_description: See what's knew!
new_arrivals_url: newarrivals/

tops_title: TOPS
tops_description: Buy some sweet tops!
tops_url: tops/

bottoms_title: BOTTOMS
bottoms_description: Buy some rockin bottoms!
bottoms_url: bottoms/

accessories_title: ACCESSORIES
accessories_description: Get your accessories here!
accessories_url: accessories/

dresses_title: DRESSES
dresses_description: Rock summer with these dresses!
dresses_url: dresses/

collections:
  newarrivals:
    output: true
  tops:
    output: true
  bottoms:
    output: true
  accessories:
    output: true
  dresses:
    output: true

shopify_script_url: https://sdks.shopifycdn.com/buy-button/latest/buy-button-storefront.min.js
shopify_domain: noble-street-boutique.myshopify.com
shopify_api_key: 49534acab58e1ab4fee682d65da8454e
shopify_app_id: 6

url: https://noblestreetboutique.com
#url: http://localhost:4000/
baseurl:

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
